/* ============================================================
   tours-data.js — All tour packages content
   ============================================================ */

const IMG = 'images/';

const TOURS = {

  /* ── UGANDA ─────────────────────────────────────────── */

  'uganda-15-days': {
    id: 'uganda-15-days',
    country: 'Uganda',
    title: '15 Days Uganda Safari',
    subtitle: 'The ultimate Uganda experience — gorillas, chimps, savannah wildlife, and the mighty Nile.',
    duration: '15 Days / 14 Nights',
    groupSize: '2–12 Travelers',
    bestSeason: 'Jun–Sep, Dec–Feb',
    difficulty: 'Moderate',
    accommodation: 'Mid-range to Luxury Lodges',
    image: IMG + 'Uganda-Wildlife-Safari-720x480.jpg',
    heroImage: IMG + 'Uganda-Wildlife-Safari-720x480.jpg',
    highlights: [
      'Gorilla trekking in Bwindi Impenetrable Forest',
      'Chimpanzee trekking in Kibale National Park',
      'Wildlife game drives in Queen Elizabeth NP',
      'Boat cruise on the Kazinga Channel',
      'Murchison Falls & Nile boat cruise',
      'Tree-climbing lions in Ishasha Sector',
    ],
    overview: `Uganda's richness of wildlife and landscapes is unmatched. This 15-day safari takes you deep into the heart of the Pearl of Africa, encountering mountain gorillas in the ancient forests of Bwindi, tracking chimpanzees through Kibale's dense canopy, watching herds of elephants and buffaloes roam Queen Elizabeth National Park, and cruising the Nile below the thundering Murchison Falls. A journey that stays with you forever.`,
    itinerary: [
      { day: 1, title: 'Arrival in Kampala', desc: 'Welcome to Uganda! Transfer from Entebbe Airport to Kampala. Briefing with your Lechwe Safari guide. Overnight in Kampala.' },
      { day: 2, title: 'Kampala to Kibale National Park', desc: 'Drive southwest to Kibale National Park, arriving at your lodge. Afternoon walk in the forest.' },
      { day: 3, title: 'Chimpanzee Trekking, Kibale', desc: 'Full-day chimp trekking experience in Kibale Forest. Afternoon community visit to Bigodi Wetland Sanctuary.' },
      { day: 4, title: 'Kibale to Queen Elizabeth NP', desc: 'Transfer to Queen Elizabeth National Park via the Crater Lakes region. Afternoon game drive on the Kasenyi plains.' },
      { day: 5, title: 'Game Drive & Kazinga Channel Cruise', desc: 'Morning game drive in Kasenyi. Afternoon boat cruise on the Kazinga Channel — hippos, crocodiles, and thousands of birds.' },
      { day: 6, title: 'Ishasha Sector — Tree-Climbing Lions', desc: 'Game drive to Ishasha Sector, home of Uganda\'s famous tree-climbing lions lazing on fig tree branches.' },
      { day: 7, title: 'Ishasha to Bwindi Impenetrable Forest', desc: 'Scenic drive to Bwindi. Check in to your lodge and acclimatize for tomorrow\'s gorilla trek.' },
      { day: 8, title: 'Gorilla Trekking — Bwindi', desc: 'The highlight of Uganda! Trek through ancient rainforest to spend a precious hour with a mountain gorilla family.' },
      { day: 9, title: 'Optional Gorilla Habituation or Batwa Trail', desc: 'Choose between gorilla habituation experience or the Batwa Cultural Trail — a deep dive into indigenous forest culture.' },
      { day: 10, title: 'Bwindi to Kigali (Rwanda Transfer) or Drive to Murchison', desc: 'Depending on routing, transfer to Murchison Falls via Lake Mburo or return north through central Uganda.' },
      { day: 11, title: 'Lake Mburo National Park', desc: 'Game drive in Lake Mburo — zebras, impalas, topis, and the elusive leopard. Boat ride on Lake Mburo.' },
      { day: 12, title: 'Drive to Murchison Falls NP', desc: 'Long drive north to Uganda\'s largest national park. Evening game drive along the Nile Delta.' },
      { day: 13, title: 'Murchison Falls — Game Drive & Nile Cruise', desc: 'Morning game drive for lions, elephants, and giraffes. Afternoon boat cruise to the base of Murchison Falls.' },
      { day: 14, title: 'Budongo Forest — Chimpanzee Walk', desc: 'Half-day chimp walk in Budongo Forest Reserve. Drive back towards Kampala or Entebbe.' },
      { day: 15, title: 'Departure', desc: 'Transfer to Entebbe Airport for your departure flight. End of safari.' },
    ],
    inclusions: ['Airport transfers', 'All accommodation', 'All meals (full board)', 'Expert English-speaking guide', 'Park entry fees', 'Gorilla trekking permit', 'Boat cruises', 'Game drives in 4×4 safari vehicle', 'Bottled water in vehicle'],
    exclusions: ['International flights', 'Travel insurance', 'Visa fees', 'Alcoholic beverages', 'Gratuities', 'Personal expenses'],
  },

  'uganda-12-days': {
    id: 'uganda-12-days',
    country: 'Uganda',
    title: '12 Days Uganda Gorillas, Chimps, Golden Monkeys & Wildlife Safari',
    subtitle: 'A primate paradise: gorillas, chimpanzees, and golden monkeys in one extraordinary journey.',
    duration: '12 Days / 11 Nights',
    groupSize: '2–10 Travelers',
    bestSeason: 'Jun–Sep, Dec–Feb',
    difficulty: 'Moderate',
    accommodation: 'Mid-range to Luxury Lodges',
    image: IMG + 'Golden-Monkey-Trekking-in-Uganda-720x450.jpg',
    heroImage: IMG + 'Golden-Monkey-Trekking-in-Uganda-720x450.jpg',
    highlights: [
      'Gorilla trekking in Bwindi Impenetrable Forest',
      'Golden monkey trekking in Mgahinga NP',
      'Chimpanzee trekking in Kibale NP',
      'Wildlife drives in Queen Elizabeth NP',
      'Kazinga Channel boat cruise',
      'Batwa cultural experience',
    ],
    overview: `This 12-day safari is a primatologist's dream. Uganda hosts more primate species than almost any other country on Earth. This itinerary is designed to let you encounter three of the most extraordinary — mountain gorillas in ancient Bwindi, energetic golden monkeys in the volcanic slopes of Mgahinga, and chimpanzees in the world-class Kibale Forest. Between primate encounters, superb wildlife drives complete an unforgettable East African adventure.`,
    itinerary: [
      { day: 1, title: 'Arrival — Entebbe', desc: 'Arrival and transfer to Entebbe or Kampala. Welcome dinner with your guide.' },
      { day: 2, title: 'Kampala to Kibale Forest', desc: 'Drive to Kibale National Park through Uganda\'s rolling tea plantations. Afternoon crater lakes tour.' },
      { day: 3, title: 'Chimpanzee Trekking — Kibale', desc: 'Morning chimp trek in Kibale — the best place in the world to track wild chimpanzees. Over 1,500 chimps inhabit this forest.' },
      { day: 4, title: 'Kibale to Queen Elizabeth NP', desc: 'Transfer to Queen Elizabeth NP. Afternoon game drive on Kasenyi Plains.' },
      { day: 5, title: 'Queen Elizabeth — Full Day Safari', desc: 'Morning game drive and afternoon 2-hour Kazinga Channel cruise for hippos, elephants, and flamingos.' },
      { day: 6, title: 'Drive to Bwindi via Ishasha', desc: 'Pass through Ishasha Sector in search of tree-climbing lions before arriving at Bwindi.' },
      { day: 7, title: 'Gorilla Trekking — Bwindi', desc: 'The crown jewel of Uganda — trekking to spend one magical hour with a habituated mountain gorilla family.' },
      { day: 8, title: 'Bwindi to Mgahinga Gorilla NP', desc: 'Drive to Mgahinga NP. Afternoon briefing for the golden monkey trek.' },
      { day: 9, title: 'Golden Monkey Trekking — Mgahinga', desc: 'Trek through bamboo forests to find the rare and acrobatic golden monkeys — endemic to the Virunga Volcanoes.' },
      { day: 10, title: 'Batwa Experience & Drive North', desc: 'Morning Batwa Pygmy cultural experience. Begin return journey through southwest Uganda.' },
      { day: 11, title: 'Lake Mburo National Park', desc: 'Afternoon game drive in Lake Mburo — the only place in Uganda to see zebra and impala.' },
      { day: 12, title: 'Return to Kampala — Departure', desc: 'Morning drive to Kampala/Entebbe. Transfer to airport for departure. End of safari.' },
    ],
    inclusions: ['Airport transfers', 'All accommodation', 'Full-board meals', 'Expert guide', 'Park entry fees', 'Gorilla & golden monkey permits', 'Chimp trekking fees', 'All game drives', 'Kazinga Channel cruise', 'Bottled water'],
    exclusions: ['International flights', 'Travel insurance', 'Visa fees', 'Drinks', 'Tips & gratuities'],
  },

  'uganda-10-days': {
    id: 'uganda-10-days',
    country: 'Uganda',
    title: '10 Days Uganda Gorillas, Chimps & Wildlife Safari',
    subtitle: 'Gorilla families, chimpanzee forests, and East African savannah wildlife in ten days.',
    duration: '10 Days / 9 Nights',
    groupSize: '2–12 Travelers',
    bestSeason: 'Jun–Sep, Dec–Feb',
    difficulty: 'Moderate',
    accommodation: 'Mid-range Lodges',
    image: IMG + '12-days-uganda-gorilla-wildlife-safari-720x480.jpg',
    heroImage: IMG + '12-days-uganda-gorilla-wildlife-safari-720x480.jpg',
    highlights: [
      'Gorilla trekking in Bwindi',
      'Chimpanzee trekking in Kibale',
      'Queen Elizabeth NP game drives',
      'Kazinga Channel boat cruise',
      'Crater Lakes experience',
    ],
    overview: `Ten days is the sweet spot for Uganda — enough time to immerse yourself in both the primates and the savannah wildlife. You'll track chimpanzees in Kibale, encounter mountain gorillas in Bwindi's primeval forest, cruise the Kazinga Channel amid hippos and elephants, and drive through the wide-open savannahs of Queen Elizabeth National Park. A deeply satisfying East African safari.`,
    itinerary: [
      { day: 1, title: 'Arrival in Uganda', desc: 'Airport pickup and transfer to Entebbe/Kampala. Evening briefing.' },
      { day: 2, title: 'Kampala to Kibale', desc: 'Scenic drive to Fort Portal and Kibale. Afternoon community tour.' },
      { day: 3, title: 'Chimpanzee Trek — Kibale', desc: 'Full morning chimpanzee trek in Kibale Forest. Afternoon Bigodi Wetland walk.' },
      { day: 4, title: 'Drive to Queen Elizabeth NP', desc: 'Drive south past the beautiful Crater Lakes region to Queen Elizabeth NP. Afternoon game drive.' },
      { day: 5, title: 'Queen Elizabeth — Game Drive & Cruise', desc: 'Morning game drive, afternoon Kazinga Channel boat cruise.' },
      { day: 6, title: 'Ishasha — Tree-Climbing Lions & Drive to Bwindi', desc: 'Early morning game drive in Ishasha Sector for tree-climbing lions. Afternoon drive to Bwindi.' },
      { day: 7, title: 'Gorilla Trekking — Bwindi', desc: 'Pre-dawn briefing, then trek into the forest for an unforgettable hour with mountain gorillas.' },
      { day: 8, title: 'Bwindi — Relaxation & Nature Walk', desc: 'Optional nature walk around Bwindi or Batwa cultural experience. Scenic afternoon.' },
      { day: 9, title: 'Return Drive — Lake Mburo', desc: 'Drive north to Lake Mburo for a quick game drive. Continue to Kampala.' },
      { day: 10, title: 'Departure from Entebbe', desc: 'Transfer to Entebbe Airport. End of safari.' },
    ],
    inclusions: ['Airport transfers', 'All accommodation', 'Full-board meals', 'Expert guide', 'Park fees', 'Gorilla permit', 'Chimp trekking', 'Game drives & boat cruise', 'Bottled water'],
    exclusions: ['International flights', 'Travel insurance', 'Visas', 'Drinks', 'Gratuities'],
  },

  'uganda-8-days': {
    id: 'uganda-8-days',
    country: 'Uganda',
    title: '8 Days Uganda Wildlife Safari',
    subtitle: 'An action-packed introduction to Uganda\'s iconic wildlife parks and the Nile.',
    duration: '8 Days / 7 Nights',
    groupSize: '2–14 Travelers',
    bestSeason: 'Year-round',
    difficulty: 'Easy to Moderate',
    accommodation: 'Mid-range Lodges',
    image: IMG + 'Uganda-Wildlife-Safari-720x480.jpg',
    heroImage: IMG + 'Uganda-Wildlife-Safari-720x480.jpg',
    highlights: [
      'Murchison Falls & Nile boat cruise',
      'Game drives in Murchison Falls NP',
      'Chimpanzee trekking in Kibale',
      'Gorilla trekking in Bwindi',
      'Queen Elizabeth NP boat cruise',
    ],
    overview: `Eight days is the perfect quick-immersion into Uganda's wildlife riches. This itinerary covers the greatest hits — Murchison Falls (where the Nile forces itself through a 7-meter gap), Kibale's chimpanzees, and the legendary mountain gorillas of Bwindi. Ideal for first-time visitors who want to experience Uganda's wildlife diversity within a compact timeframe.`,
    itinerary: [
      { day: 1, title: 'Arrival — Kampala/Entebbe', desc: 'Arrival and transfer. Welcome briefing and overnight in Entebbe.' },
      { day: 2, title: 'Drive to Murchison Falls NP', desc: 'Drive north to Murchison Falls National Park. Afternoon game drive.' },
      { day: 3, title: 'Murchison — Game Drive & Nile Cruise', desc: 'Morning game drive (elephants, lions, giraffes). Afternoon boat cruise to the base of the mighty Murchison Falls.' },
      { day: 4, title: 'Murchison to Kibale', desc: 'Long but scenic drive south through Uganda\'s heartland to Kibale Forest.' },
      { day: 5, title: 'Chimpanzee Trekking — Kibale', desc: 'Half-day chimp trek, afternoon visit to the Crater Lakes.' },
      { day: 6, title: 'Kibale to Bwindi', desc: 'Drive south through Queen Elizabeth NP. Brief game drive. Continue to Bwindi.' },
      { day: 7, title: 'Gorilla Trekking — Bwindi', desc: 'An extraordinary morning face-to-face with mountain gorillas in the jungle.' },
      { day: 8, title: 'Bwindi to Kampala — Departure', desc: 'Long drive back to Kampala/Entebbe. Departure.' },
    ],
    inclusions: ['Airport transfers', 'All accommodation', 'Full-board meals', 'Guide', 'Park fees', 'Gorilla permit', 'Chimp permit', 'All game drives', 'Nile cruise', 'Water'],
    exclusions: ['Flights', 'Insurance', 'Visas', 'Alcohol', 'Tips'],
  },

  /* ── RWANDA ──────────────────────────────────────────── */

  'rwanda-7-days': {
    id: 'rwanda-7-days',
    country: 'Rwanda',
    title: '7 Days Rwanda Safari',
    subtitle: 'Gorillas, golden monkeys, chimpanzees, and Big 5 game drives — Rwanda\'s greatest wildlife in one week.',
    duration: '7 Days / 6 Nights',
    groupSize: '2–10 Travelers',
    bestSeason: 'Jun–Sep, Dec–Feb',
    difficulty: 'Moderate',
    accommodation: 'Mid-range to Luxury',
    image: IMG + 'Gorilla-Tour-rwanda-720x450.jpg',
    heroImage: IMG + 'Gorilla-Tour-rwanda-720x450.jpg',
    highlights: [
      'Gorilla trekking in Volcanoes NP',
      'Golden monkey trekking',
      'Chimpanzee trekking in Nyungwe',
      'Big 5 game drive in Akagera NP',
      'Kigali city tour',
    ],
    overview: `In seven days, Rwanda reveals itself as one of Africa's most remarkable destinations. Begin in Kigali — clean, safe, and surprisingly vibrant. Then venture to the misty Volcanoes National Park for gorilla and golden monkey encounters. Nyungwe Forest offers chimpanzee trekking through one of Africa's oldest rainforests. Finally, Akagera National Park delivers classic savannah game drives with all of the Big 5. Rwanda packs extraordinary biodiversity into a tiny, beautifully managed country.`,
    itinerary: [
      { day: 1, title: 'Arrival in Kigali', desc: 'Arrive at Kigali International Airport. Transfer to hotel. Afternoon Kigali city tour including the Genocide Memorial. Welcome dinner.' },
      { day: 2, title: 'Kigali to Volcanoes NP', desc: 'Drive northwest to Volcanoes National Park (2.5 hours). Check in to lodge. Afternoon briefing for tomorrow\'s gorilla trek.' },
      { day: 3, title: 'Gorilla Trekking — Volcanoes NP', desc: 'Early morning briefing at park headquarters. Trek into the volcanic forest to spend one magical hour with a habituated mountain gorilla family — a life-changing experience.' },
      { day: 4, title: 'Golden Monkey Trekking', desc: 'Trek through bamboo forests of Volcanoes NP to encounter the playful, colourful golden monkeys endemic to the Virunga range.' },
      { day: 5, title: 'Volcanoes to Nyungwe Forest', desc: 'Scenic drive across Rwanda\'s Thousand Hills to Nyungwe Forest National Park. Afternoon canopy walk.' },
      { day: 6, title: 'Chimpanzee Trekking — Nyungwe', desc: 'Morning chimpanzee trek in Nyungwe — one of Africa\'s oldest rainforests with 13 primate species.' },
      { day: 7, title: 'Nyungwe to Kigali — Departure', desc: 'Return to Kigali via Akagera (optional stop for game drive). Departure flight.' },
    ],
    inclusions: ['Airport transfers', 'All accommodation', 'Full-board meals', 'Expert guide', 'Park fees', 'Gorilla permit', 'Golden monkey permit', 'Chimp permit', 'Canopy walk', 'Bottled water'],
    exclusions: ['International flights', 'Travel insurance', 'Visa', 'Drinks', 'Gratuities', 'Personal expenses'],
  },

  'rwanda-4-days': {
    id: 'rwanda-4-days',
    country: 'Rwanda',
    title: '4 Days Rwanda Chimps & Gorilla Tour',
    subtitle: 'A compact dual-primate adventure — gorillas and chimpanzees in Rwanda\'s most iconic forests.',
    duration: '4 Days / 3 Nights',
    groupSize: '2–10 Travelers',
    bestSeason: 'Jun–Sep, Dec–Feb',
    difficulty: 'Moderate',
    accommodation: 'Mid-range Lodges',
    image: IMG + 'Rwanda-Chimps-trekking-720x450.jpg',
    heroImage: IMG + 'Rwanda-Chimps-trekking-720x450.jpg',
    highlights: [
      'Gorilla trekking in Volcanoes NP',
      'Chimpanzee trekking in Nyungwe',
      'Nyungwe canopy walk',
      'Kigali cultural exploration',
    ],
    overview: `Four days is all you need for Rwanda's most iconic primate encounters. This tight but deeply rewarding itinerary covers both gorilla trekking in the Virunga volcanoes and chimpanzee tracking in ancient Nyungwe Forest — a rare dual-primate experience that few destinations in the world can offer. Perfect as a standalone trip or as an extension of a longer East Africa journey.`,
    itinerary: [
      { day: 1, title: 'Arrival in Kigali & Nyungwe', desc: 'Arrive Kigali. Drive 5 hours south to Nyungwe Forest. Check in to lodge. Evening briefing.' },
      { day: 2, title: 'Chimpanzee Trekking — Nyungwe', desc: 'Early morning chimp trek into one of Africa\'s oldest and most biodiverse tropical forests. Afternoon canopy walk (suspended bridge above the forest canopy).' },
      { day: 3, title: 'Nyungwe to Volcanoes NP — Gorilla Trek', desc: 'Morning drive north to Volcanoes NP (passing through Kigali). Afternoon gorilla trek briefing and trek — or trek early the following morning.' },
      { day: 4, title: 'Volcanoes to Kigali — Departure', desc: 'Return to Kigali. Optional Genocide Memorial visit. Transfer to airport for departure.' },
    ],
    inclusions: ['Airport transfers', 'All accommodation', 'Full-board meals', 'Guide', 'Park fees', 'Gorilla permit', 'Chimp permit', 'Canopy walk', 'Bottled water'],
    exclusions: ['Flights', 'Travel insurance', 'Visa', 'Drinks', 'Tips'],
  },

  'rwanda-3-days': {
    id: 'rwanda-3-days',
    country: 'Rwanda',
    title: '3 Days Gorilla Trekking in Rwanda',
    subtitle: 'The ultimate short-break safari: mountain gorillas in Volcanoes National Park.',
    duration: '3 Days / 2 Nights',
    groupSize: '2–8 Travelers',
    bestSeason: 'Year-round',
    difficulty: 'Moderate',
    accommodation: 'Luxury & Mid-range',
    image: IMG + 'Gorilla-Tour-rwanda-720x450.jpg',
    heroImage: IMG + 'Gorilla-Tour-rwanda-720x450.jpg',
    highlights: [
      'Gorilla trekking in Volcanoes NP',
      'Visit to Kigali Genocide Memorial',
      'Scenic Virunga volcano landscapes',
    ],
    overview: `Three days is the minimum — and for many travelers, the perfect — duration for a gorilla trekking experience in Rwanda. From Kigali, Volcanoes National Park is just 2.5 hours. This short-break itinerary is ideal for travelers who want to combine a gorilla experience with business travel or a broader East Africa holiday. Rwanda's efficiency, safety, and stunning landscapes make it the perfect gorilla destination.`,
    itinerary: [
      { day: 1, title: 'Arrival in Kigali', desc: 'Arrive Kigali Airport. Transfer to hotel. Optional Kigali Genocide Memorial visit. Briefing dinner.' },
      { day: 2, title: 'Gorilla Trekking — Volcanoes NP', desc: 'Early start. Drive to Volcanoes NP. Briefing at park HQ. Begin trek through bamboo and dense forest to find your gorilla family. Spend one hour watching, photographing, and connecting with these gentle giants. Return to lodge for celebration dinner.' },
      { day: 3, title: 'Return to Kigali — Departure', desc: 'Morning at leisure. Drive back to Kigali. Optional city tour. Transfer to airport.' },
    ],
    inclusions: ['Airport transfers', 'All accommodation', 'Full-board meals', 'Expert guide', 'Park entry fees', 'Gorilla trekking permit', 'Bottled water'],
    exclusions: ['International flights', 'Travel insurance', 'Rwanda visa', 'Drinks', 'Gratuities'],
  },

  /* ── KENYA ───────────────────────────────────────────── */

  'kenya-10-days': {
    id: 'kenya-10-days',
    country: 'Kenya',
    title: '10 Days Safari in Kenya',
    subtitle: 'Maasai Mara, Amboseli, Nakuru, and Naivasha — Kenya\'s finest wildlife destinations.',
    duration: '10 Days / 9 Nights',
    groupSize: '2–12 Travelers',
    bestSeason: 'Jul–Oct (Migration), Jan–Feb',
    difficulty: 'Easy',
    accommodation: 'Mid-range to Luxury Camps',
    image: IMG + '10-Days-safari-in-Kenya-720x450.jpg',
    heroImage: IMG + '10-Days-safari-in-Kenya-720x450.jpg',
    highlights: [
      'Maasai Mara — Big 5 game drives',
      'Possible Great Migration sighting (Jul–Oct)',
      'Amboseli — elephants and Kilimanjaro views',
      'Lake Nakuru — flamingos and rhinos',
      'Lake Naivasha — boat ride with hippos',
      'Nairobi National Park',
    ],
    overview: `Kenya is the birthplace of the safari, and this 10-day journey covers its greatest highlights. From the wildlife-laden savannahs of the Maasai Mara to the surreal flamingo-pink shores of Lake Nakuru, from Amboseli's elephant herds against the backdrop of Kilimanjaro to the lush shores of Lake Naivasha, Kenya delivers iconic African experiences at every turn.`,
    itinerary: [
      { day: 1, title: 'Arrival — Nairobi', desc: 'Arrive Jomo Kenyatta International Airport. Transfer to Nairobi hotel. Briefing and welcome dinner.' },
      { day: 2, title: 'Nairobi NP & Drive to Amboseli', desc: 'Morning game drive in Nairobi National Park. Afternoon drive to Amboseli National Park.' },
      { day: 3, title: 'Amboseli NP — Elephants & Kilimanjaro', desc: 'Full day in Amboseli. Morning and afternoon game drives. Watch herds of elephants against the iconic backdrop of Mt Kilimanjaro.' },
      { day: 4, title: 'Amboseli to Lake Naivasha', desc: 'Drive north through Nairobi to the Great Rift Valley. Afternoon boat ride on Lake Naivasha.' },
      { day: 5, title: 'Lake Naivasha & Lake Nakuru', desc: 'Morning walk at Hell\'s Gate NP (cycling option). Afternoon game drive in Lake Nakuru NP — rhinos, flamingos, and leopards.' },
      { day: 6, title: 'Lake Nakuru to Maasai Mara', desc: 'Drive to the Maasai Mara. Afternoon game drive in one of the world\'s greatest wildlife reserves.' },
      { day: 7, title: 'Full Day — Maasai Mara', desc: 'Full day of game drives. Witness the Big 5 on open savannah. Possible Great Migration river crossing (seasonal).' },
      { day: 8, title: 'Maasai Mara — Morning Safari & Maasai Village', desc: 'Early morning game drive. Afternoon Maasai village cultural visit.' },
      { day: 9, title: 'Maasai Mara to Nairobi', desc: 'Final morning game drive. Drive back to Nairobi. Evening at leisure.' },
      { day: 10, title: 'Departure', desc: 'Transfer to Nairobi airport for departure flight.' },
    ],
    inclusions: ['Airport transfers', 'All accommodation', 'Full-board meals', 'Safari guide', 'Park fees', 'All game drives', 'Lake Naivasha boat ride', 'Bottled water'],
    exclusions: ['International flights', 'Travel insurance', 'Kenya visa (eTA)', 'Drinks', 'Hot air balloon (optional extra)', 'Gratuities'],
  },

  'kenya-8-days': {
    id: 'kenya-8-days',
    country: 'Kenya',
    title: '8 Days Kenya Safari',
    subtitle: 'Maasai Mara magic, the Rift Valley lakes, and Amboseli\'s elephant paradise.',
    duration: '8 Days / 7 Nights',
    groupSize: '2–12 Travelers',
    bestSeason: 'Jul–Oct, Jan–Feb',
    difficulty: 'Easy',
    accommodation: 'Mid-range Camps & Lodges',
    image: IMG + '8-days-kenya-adventure-720x450.jpg',
    heroImage: IMG + '8-days-kenya-adventure-720x450.jpg',
    highlights: [
      'Maasai Mara National Reserve',
      'Lake Nakuru — flamingos and rhinos',
      'Amboseli — elephants with Kilimanjaro',
      'Cultural Maasai village visit',
    ],
    overview: `Eight days in Kenya strikes the perfect balance — enough time to experience the Maasai Mara's legendary game viewing, the flamingo spectacle of Lake Nakuru, and the unforgettable sight of Amboseli's elephants beneath Kilimanjaro. This safari is ideal for first-time visitors to Kenya seeking an efficient and comprehensive East African experience.`,
    itinerary: [
      { day: 1, title: 'Arrival — Nairobi', desc: 'Airport pickup, transfer to Nairobi hotel. Welcome dinner and briefing.' },
      { day: 2, title: 'Nairobi to Amboseli', desc: 'Drive south to Amboseli NP. Afternoon game drive.' },
      { day: 3, title: 'Full Day Amboseli', desc: 'Dawn and dusk game drives. Spectacular elephant and Kilimanjaro photo opportunities.' },
      { day: 4, title: 'Amboseli to Lake Nakuru', desc: 'Drive north through Nairobi. Afternoon game drive in Lake Nakuru NP — famous for its flamingo-fringed shores and dense rhino population.' },
      { day: 5, title: 'Lake Nakuru to Maasai Mara', desc: 'Drive west to the Maasai Mara. Afternoon game drive.' },
      { day: 6, title: 'Full Day — Maasai Mara', desc: 'All-day game drives. The Big 5, cheetahs, and in season, the dramatic wildebeest migration river crossings.' },
      { day: 7, title: 'Maasai Mara — Cultural Visit & Drive to Nairobi', desc: 'Morning game drive and Maasai cultural village. Afternoon drive to Nairobi.' },
      { day: 8, title: 'Departure', desc: 'Transfer to airport. End of safari.' },
    ],
    inclusions: ['Airport transfers', 'All accommodation', 'Full-board meals', 'Guide', 'Park fees', 'All game drives', 'Water'],
    exclusions: ['International flights', 'Insurance', 'Visa', 'Drinks', 'Tips'],
  },

  'kenya-5-days': {
    id: 'kenya-5-days',
    country: 'Kenya',
    title: '5 Days Kenya Safari — Naivasha, Nakuru & Maasai Mara',
    subtitle: 'Kenya\'s three most iconic wildlife destinations in a compact five-day adventure.',
    duration: '5 Days / 4 Nights',
    groupSize: '2–14 Travelers',
    bestSeason: 'Year-round',
    difficulty: 'Easy',
    accommodation: 'Mid-range',
    image: IMG + 'kenya-safari-720x450.jpg',
    heroImage: IMG + 'kenya-safari-720x450.jpg',
    highlights: [
      'Lake Naivasha — hippo boat ride',
      'Hell\'s Gate National Park (cycling)',
      'Lake Nakuru — flamingos and rhinos',
      'Maasai Mara — Big 5 game drives',
    ],
    overview: `Five days, three incredible destinations. This compact Kenya safari whisks you through the Great Rift Valley — hippo-filled Lake Naivasha, the flamingo shores of Nakuru, and the wildlife-dense plains of the Maasai Mara. Ideal as a standalone safari or a tack-on to a Uganda or Rwanda gorilla trip, this itinerary delivers Kenya's most iconic wildlife moments efficiently.`,
    itinerary: [
      { day: 1, title: 'Nairobi to Lake Naivasha', desc: 'Arrive Nairobi, drive to Lake Naivasha. Afternoon boat ride among hippos and 400 bird species.' },
      { day: 2, title: 'Hell\'s Gate & Lake Nakuru', desc: 'Morning cycling/walking in Hell\'s Gate National Park — one of Kenya\'s few places you explore on foot or bike. Afternoon drive to Lake Nakuru for flamingo and rhino game drive.' },
      { day: 3, title: 'Lake Nakuru to Maasai Mara', desc: 'Drive to the Maasai Mara. Afternoon game drive on the vast open savannah.' },
      { day: 4, title: 'Full Day — Maasai Mara', desc: 'Morning and afternoon game drives. Look for lions, leopards, cheetahs, and elephants on the endless Mara plains.' },
      { day: 5, title: 'Maasai Mara to Nairobi — Departure', desc: 'Final game drive, then drive to Nairobi. Airport transfer. Departure.' },
    ],
    inclusions: ['Airport transfers', 'All accommodation', 'Full-board meals', 'Guide', 'Park fees', 'Boat ride', 'All game drives', 'Water'],
    exclusions: ['Flights', 'Insurance', 'Visa', 'Drinks', 'Tips', 'Cycling rental (optional)'],
  },

  /* ── TANZANIA ────────────────────────────────────────── */

  'tanzania-9-days': {
    id: 'tanzania-9-days',
    country: 'Tanzania',
    title: '9 Days Adventure Safari in Tanzania',
    subtitle: 'Serengeti, Ngorongoro Crater, Tarangire, and the spice island of Zanzibar.',
    duration: '9 Days / 8 Nights',
    groupSize: '2–12 Travelers',
    bestSeason: 'Jun–Oct, Jan–Mar',
    difficulty: 'Easy',
    accommodation: 'Mid-range Camps & Lodges',
    image: IMG + '9Days-Adventure-Safari-in-Tanzania-720x450.jpg',
    heroImage: IMG + '9Days-Adventure-Safari-in-Tanzania-720x450.jpg',
    highlights: [
      'Serengeti National Park — Big 5',
      'Ngorongoro Crater game drive',
      'Tarangire — elephant herds',
      'Zanzibar beach extension',
      'Maasai cultural experience',
    ],
    overview: `Tanzania is legendary. The Serengeti alone is reason enough to visit — an ocean of golden grass stretching to every horizon, teeming with lions, leopards, elephants, and the world\'s greatest wildlife spectacle. Combined with the staggering Ngorongoro Crater, the elephant paradise of Tarangire, and a Zanzibar beach finale, this 9-day adventure delivers the full Tanzania experience.`,
    itinerary: [
      { day: 1, title: 'Arrival — Kilimanjaro Airport', desc: 'Arrive at Kilimanjaro International Airport. Transfer to Arusha. Welcome dinner and safari briefing.' },
      { day: 2, title: 'Arusha to Tarangire NP', desc: 'Drive to Tarangire National Park. Afternoon game drive. Tarangire is famous for its enormous baobab trees and elephant herds — up to 3,000 elephants.' },
      { day: 3, title: 'Tarangire to Serengeti NP', desc: 'Morning game drive in Tarangire. Drive to the Serengeti — one of the world\'s most iconic wildlife reserves. Afternoon game drive.' },
      { day: 4, title: 'Full Day — Serengeti', desc: 'All-day game drives on the endless Serengeti plains. Search for the Big 5, wild dogs, and cheetahs.' },
      { day: 5, title: 'Serengeti — Optional Balloon Safari', desc: 'Dawn hot-air balloon safari (optional, additional cost) over the Serengeti. Afternoon game drive.' },
      { day: 6, title: 'Serengeti to Ngorongoro Crater', desc: 'Morning game drive. Drive to the Ngorongoro Conservation Area. Afternoon game drive into the crater — a collapsed volcanic caldera teeming with wildlife.' },
      { day: 7, title: 'Full Day — Ngorongoro Crater', desc: 'Full-day game drive inside the crater. All Big 5 regularly seen. Black rhinos are regularly spotted here.' },
      { day: 8, title: 'Ngorongoro to Zanzibar', desc: 'Morning drive to Kilimanjaro Airport. Fly to Zanzibar. Afternoon beach arrival. Relax on white-sand beaches.' },
      { day: 9, title: 'Zanzibar — Departure', desc: 'Morning at leisure on Zanzibar\'s beaches. Afternoon departure flight.' },
    ],
    inclusions: ['Airport transfers', 'All accommodation', 'Full-board (Safari); B&B (Zanzibar)', 'Guide', 'Park fees', 'All game drives', 'Zanzibar domestic flight', 'Water'],
    exclusions: ['International flights', 'Insurance', 'Tanzania visa', 'Drinks', 'Balloon safari', 'Tips'],
  },

  'tanzania-8-days-wildebeest': {
    id: 'tanzania-8-days-wildebeest',
    country: 'Tanzania',
    title: '8 Days Tanzania Wildebeest Migration Safari',
    subtitle: 'Witness one of nature\'s greatest spectacles — millions of wildebeest crossing the Serengeti.',
    duration: '8 Days / 7 Nights',
    groupSize: '2–10 Travelers',
    bestSeason: 'Jul–Oct (Migration Season)',
    difficulty: 'Easy',
    accommodation: 'Migration Camps',
    image: IMG + 'Wildebeest-migration-Tanzania-720x450.jpg',
    heroImage: IMG + 'Wildebeest-migration-Tanzania-720x450.jpg',
    highlights: [
      'Great Wildebeest Migration river crossings',
      'Serengeti game drives',
      'Ngorongoro Crater',
      'Mara River crossing (Jul–Oct)',
      'Predator action — lions & crocodiles',
    ],
    overview: `There is nothing else like the Great Wildebeest Migration on Earth. Over 1.5 million wildebeest, 200,000 zebra, and 400,000 gazelle move in an endless cycle across the Serengeti and Maasai Mara. This 8-day safari is timed for the peak crossing season (July–October) when herds plunge into the Mara River in chaotic, awe-inspiring crossings — while crocodiles and lions wait. A wildlife spectacle that leaves every guest speechless.`,
    itinerary: [
      { day: 1, title: 'Arrival — Arusha', desc: 'Arrive Kilimanjaro Airport. Transfer to Arusha for overnight. Briefing dinner.' },
      { day: 2, title: 'Arusha to Serengeti (Northern)', desc: 'Drive or fly to the northern Serengeti — the heart of migration territory. Afternoon game drive.' },
      { day: 3, title: 'Serengeti — Migration Game Drives', desc: 'Full day following the herds and searching for crossing points on the Mara River. Lions and hyenas are in constant action.' },
      { day: 4, title: 'Serengeti — Mara River Crossings', desc: 'Park at the Mara River and wait for the drama. Wildebeest gather in thousands before plunging into crocodile-infested waters in chaotic, breathtaking crossings.' },
      { day: 5, title: 'Serengeti Central — Full Game Drive', desc: 'Game drives through central Serengeti. Look for leopards in acacia trees, cheetah families, and elephant herds.' },
      { day: 6, title: 'Serengeti to Ngorongoro', desc: 'Morning Serengeti game drive. Drive to Ngorongoro Conservation Area. Arrive at crater rim lodge.' },
      { day: 7, title: 'Ngorongoro Crater — Full Day', desc: 'Full day inside Ngorongoro Crater — the world\'s largest intact volcanic caldera. All Big 5 regularly spotted including the endangered black rhino.' },
      { day: 8, title: 'Return to Arusha — Departure', desc: 'Morning drive to Arusha. Lunch stop. Transfer to airport for departure.' },
    ],
    inclusions: ['All transfers', 'All accommodation', 'Full-board meals', 'Expert guide', 'Park fees', 'All game drives', 'Water'],
    exclusions: ['International flights', 'Insurance', 'Visa', 'Drinks', 'Tips', 'Optional flights within Tanzania'],
  },

  'tanzania-6-days': {
    id: 'tanzania-6-days',
    country: 'Tanzania',
    title: '6 Days Classic Tanzania Safari — Tarangire, Serengeti & Ngorongoro',
    subtitle: 'Tanzania\'s three crown jewels in an efficient and spectacular six-day circuit.',
    duration: '6 Days / 5 Nights',
    groupSize: '2–14 Travelers',
    bestSeason: 'Year-round',
    difficulty: 'Easy',
    accommodation: 'Mid-range Camps',
    image: IMG + 'Tarangire-National-Park-Wildlife-720x450.jpg',
    heroImage: IMG + 'Tarangire-National-Park-Wildlife-720x450.jpg',
    highlights: [
      'Tarangire NP — elephant paradise',
      'Serengeti — Big 5 game drives',
      'Ngorongoro Crater — black rhino',
      'Maasai Boma cultural visit',
    ],
    overview: `Tanzania\'s Northern Circuit is among the greatest wildlife destinations on Earth. This 6-day classic covers the three parks no Tanzania safari should miss: Tarangire's ancient baobabs and massive elephant herds, the iconic Serengeti with its endless horizons and incredible predator density, and the world-heritage Ngorongoro Crater — a natural amphitheater protecting one of Africa's last black rhino populations. Perfect first-time Tanzania safari.`,
    itinerary: [
      { day: 1, title: 'Arusha — Arrival & Briefing', desc: 'Arrive Kilimanjaro Airport. Transfer to Arusha. Briefing dinner.' },
      { day: 2, title: 'Tarangire National Park', desc: 'Drive to Tarangire NP. Morning and afternoon game drives amid ancient baobab trees and huge elephant herds.' },
      { day: 3, title: 'Tarangire to Serengeti', desc: 'Game drive en route to Serengeti. Afternoon game drive on arrival.' },
      { day: 4, title: 'Full Day Serengeti', desc: 'All-day game drives. The Big 5, cheetah, wild dog, and more across the endless golden plains.' },
      { day: 5, title: 'Serengeti to Ngorongoro Crater', desc: 'Morning game drive. Drive to Ngorongoro. Afternoon crater game drive — spectacular wildlife density in a collapsed volcano.' },
      { day: 6, title: 'Ngorongoro to Arusha — Departure', desc: 'Morning crater game drive. Return to Arusha. Airport departure.' },
    ],
    inclusions: ['Airport transfers', 'All accommodation', 'Full-board meals', 'Guide', 'Park fees', 'All game drives', 'Water'],
    exclusions: ['International flights', 'Insurance', 'Visa', 'Drinks', 'Tips'],
  },

  /* ── COMBINED TOURS ──────────────────────────────────── */

  'combined-20-days': {
    id: 'combined-20-days',
    country: 'East Africa',
    title: '20 Days East Africa Gorillas & Wildlife Safari',
    subtitle: 'The ultimate East Africa journey — Uganda, Rwanda, Kenya, and Tanzania in one epic safari.',
    duration: '20 Days / 19 Nights',
    groupSize: '2–10 Travelers',
    bestSeason: 'Jun–Sep',
    difficulty: 'Moderate',
    accommodation: 'Mid-range to Luxury',
    image: IMG + 'Serengeti-Adventure-Safari-720x450.jpg',
    heroImage: IMG + 'Serengeti-Adventure-Safari-720x450.jpg',
    highlights: [
      'Gorilla trekking — Uganda & Rwanda',
      'Chimpanzee trekking in Kibale',
      'Maasai Mara — Great Migration',
      'Serengeti & Ngorongoro Crater',
      'Queen Elizabeth NP boat cruise',
      'Zanzibar beach finale',
    ],
    overview: `Twenty days to explore the best of East Africa across four extraordinary countries. Begin in Uganda — chimps in Kibale, gorillas in Bwindi, and wildlife in Queen Elizabeth. Cross to Rwanda for a second gorilla encounter in Volcanoes National Park. Fly to Kenya for the Maasai Mara's legendary game viewing. Conclude with Tanzania's Serengeti and Ngorongoro Crater before a Zanzibar beach finale. This is the grand East African safari — an experience that defines a lifetime of travel.`,
    itinerary: [
      { day: 1, title: 'Arrival — Entebbe, Uganda', desc: 'Welcome to East Africa. Transfer to Kampala/Entebbe. Briefing.' },
      { day: 2, title: 'Kampala to Kibale NP', desc: 'Drive to Fort Portal and Kibale Forest.' },
      { day: 3, title: 'Chimpanzee Trekking — Kibale', desc: 'Full chimpanzee trekking experience in the world\'s richest chimp habitat.' },
      { day: 4, title: 'Kibale to Queen Elizabeth NP', desc: 'Drive south. Afternoon game drive in Queen Elizabeth NP.' },
      { day: 5, title: 'Queen Elizabeth — Game Drive & Kazinga Cruise', desc: 'Morning game drive, afternoon boat cruise.' },
      { day: 6, title: 'Ishasha — Drive to Bwindi', desc: 'Tree-climbing lions in Ishasha. Drive to Bwindi.' },
      { day: 7, title: 'Gorilla Trekking — Bwindi, Uganda', desc: 'Uganda gorilla trekking experience.' },
      { day: 8, title: 'Bwindi to Kigali, Rwanda', desc: 'Drive/transfer to Rwanda. Welcome in Kigali.' },
      { day: 9, title: 'Kigali to Volcanoes NP', desc: 'Drive to Ruhengeri/Musanze. Volcano landscape.' },
      { day: 10, title: 'Gorilla Trekking — Rwanda', desc: 'Second gorilla encounter — different family, different experience.' },
      { day: 11, title: 'Golden Monkey Trekking', desc: 'Morning golden monkey trek in Volcanoes NP.' },
      { day: 12, title: 'Fly Kigali to Nairobi — Maasai Mara', desc: 'Morning flight to Nairobi, drive to Maasai Mara.' },
      { day: 13, title: 'Maasai Mara — Full Day Safari', desc: 'All-day game drives. Migration crossings (seasonal).' },
      { day: 14, title: 'Maasai Mara — Morning Drive & Fly to Arusha', desc: 'Morning Mara drive. Fly to Arusha, Tanzania.' },
      { day: 15, title: 'Tarangire NP', desc: 'Full-day game drive in Tarangire.' },
      { day: 16, title: 'Tarangire to Serengeti', desc: 'Drive to Serengeti. Afternoon game drive.' },
      { day: 17, title: 'Full Day — Serengeti', desc: 'All-day Serengeti game drives.' },
      { day: 18, title: 'Serengeti to Ngorongoro Crater', desc: 'Morning Serengeti drive. Ngorongoro Crater game drive.' },
      { day: 19, title: 'Fly to Zanzibar', desc: 'Morning drive to Arusha. Flight to Zanzibar. Beach.' },
      { day: 20, title: 'Zanzibar — Departure', desc: 'Relax on Zanzibar\'s shores. Departure flight.' },
    ],
    inclusions: ['All airport/inter-city transfers', 'All accommodation', 'Full-board (safari); B&B (Zanzibar)', 'Expert guides each country', 'All park fees', '2 gorilla permits (Uganda & Rwanda)', 'Chimp trekking', 'Golden monkey permit', 'All game drives', 'Domestic flights', 'Bottled water'],
    exclusions: ['International flights', 'Travel insurance', 'Visas for all countries', 'Drinks', 'Optional balloon safari', 'Gratuities'],
  },

  'combined-10-days-rwanda-tanzania': {
    id: 'combined-10-days-rwanda-tanzania',
    country: 'Rwanda & Tanzania',
    title: '10 Days Rwanda & Tanzania Safari',
    subtitle: 'From mountain gorillas in Rwanda to Serengeti lions and Zanzibar beaches in Tanzania.',
    duration: '10 Days / 9 Nights',
    groupSize: '2–10 Travelers',
    bestSeason: 'Jun–Oct',
    difficulty: 'Easy to Moderate',
    accommodation: 'Mid-range to Luxury',
    image: IMG + 'Rwanda-Safari-with-Kenya-Tanzania-720x450.jpg',
    heroImage: IMG + 'Rwanda-Safari-with-Kenya-Tanzania-720x450.jpg',
    highlights: [
      'Gorilla trekking — Volcanoes NP, Rwanda',
      'Serengeti game drives',
      'Ngorongoro Crater — black rhino',
      'Zanzibar beach finale',
    ],
    overview: `This 10-day combination pairs Rwanda's primate magic with Tanzania's legendary wildlife spectacle. Start with mountain gorillas in the misty Virunga Volcanoes, then fly south to the Serengeti for iconic lion and elephant encounters, before finishing on Zanzibar's pristine beaches. A perfectly balanced safari that combines two of East Africa's greatest wildlife destinations.`,
    itinerary: [
      { day: 1, title: 'Arrival — Kigali, Rwanda', desc: 'Arrive Kigali. Transfer to hotel. City briefing.' },
      { day: 2, title: 'Kigali to Volcanoes NP', desc: 'Drive to Ruhengeri. Lodge check-in and briefing.' },
      { day: 3, title: 'Gorilla Trekking — Volcanoes NP', desc: 'The Rwanda highlight — trek to your gorilla family in the ancient bamboo forest.' },
      { day: 4, title: 'Golden Monkey Trekking & Drive to Kigali', desc: 'Morning golden monkey trek. Afternoon return to Kigali.' },
      { day: 5, title: 'Fly Kigali to Kilimanjaro — Tarangire NP', desc: 'Morning flight to Tanzania. Drive to Tarangire NP. Afternoon game drive.' },
      { day: 6, title: 'Tarangire to Serengeti', desc: 'Game drive through Tarangire. Drive to Serengeti. Afternoon arrival game drive.' },
      { day: 7, title: 'Full Day — Serengeti', desc: 'All-day safari on the legendary Serengeti plains.' },
      { day: 8, title: 'Serengeti to Ngorongoro Crater', desc: 'Morning Serengeti drive. Drive to Ngorongoro. Afternoon crater game drive.' },
      { day: 9, title: 'Fly to Zanzibar', desc: 'Morning in Ngorongoro. Fly to Zanzibar. Afternoon beach.' },
      { day: 10, title: 'Zanzibar — Departure', desc: 'Morning leisure. Departure flight.' },
    ],
    inclusions: ['All transfers', 'All accommodation', 'Full-board (safari); B&B (Zanzibar)', 'Guides', 'All park fees', 'Gorilla permit', 'Golden monkey permit', 'All game drives', 'Domestic flights', 'Water'],
    exclusions: ['International flights', 'Insurance', 'Visas', 'Drinks', 'Tips'],
  },

  'combined-8-days-uganda-rwanda': {
    id: 'combined-8-days-uganda-rwanda',
    country: 'Uganda & Rwanda',
    title: '8 Days Uganda Rwanda Combined Gorilla Safari',
    subtitle: 'Two countries, two gorilla encounters, and the world\'s most extraordinary primate experience.',
    duration: '8 Days / 7 Nights',
    groupSize: '2–10 Travelers',
    bestSeason: 'Jun–Sep, Dec–Feb',
    difficulty: 'Moderate',
    accommodation: 'Mid-range Lodges',
    image: IMG + '12-days-uganda-gorilla-wildlife-safari-720x480.jpg',
    heroImage: IMG + '12-days-uganda-gorilla-wildlife-safari-720x480.jpg',
    highlights: [
      'Gorilla trekking — Bwindi, Uganda',
      'Gorilla trekking — Volcanoes NP, Rwanda',
      'Chimpanzee trekking — Kibale',
      'Queen Elizabeth NP wildlife drive',
      'Golden monkey trekking — Rwanda',
    ],
    overview: `Why settle for one gorilla encounter when you can have two? This 8-day combined safari crosses the Uganda-Rwanda border, allowing you to experience mountain gorillas in both countries — two different families, two completely different forest environments, and twice the magic. Add chimpanzees in Uganda's Kibale, wildlife drives in Queen Elizabeth, and golden monkeys in Rwanda's Virunga for a primate-packed adventure.`,
    itinerary: [
      { day: 1, title: 'Arrival — Entebbe, Uganda', desc: 'Arrive Uganda. Transfer to Entebbe/Kampala. Welcome briefing.' },
      { day: 2, title: 'Drive to Kibale National Park', desc: 'Scenic drive southwest. Afternoon community visit.' },
      { day: 3, title: 'Chimpanzee Trekking — Kibale', desc: 'Morning chimp trek. Afternoon Queen Elizabeth NP game drive.' },
      { day: 4, title: 'Queen Elizabeth NP — Drive to Bwindi', desc: 'Kazinga Channel cruise. Drive south to Bwindi via Ishasha.' },
      { day: 5, title: 'Gorilla Trekking — Bwindi, Uganda', desc: 'Trek into Bwindi for an hour with mountain gorillas.' },
      { day: 6, title: 'Bwindi to Volcanoes NP, Rwanda', desc: 'Cross the Uganda-Rwanda border. Drive to Ruhengeri. Afternoon golden monkey trek.' },
      { day: 7, title: 'Gorilla Trekking — Volcanoes NP, Rwanda', desc: 'Second gorilla encounter in Rwanda — a completely different forest and gorilla family experience.' },
      { day: 8, title: 'Volcanoes to Kigali — Departure', desc: 'Drive to Kigali. Optional Genocide Memorial. Airport departure.' },
    ],
    inclusions: ['All transfers', 'All accommodation', 'Full-board meals', 'Guides (both countries)', 'All park fees', '2 gorilla permits', 'Chimp permit', 'Golden monkey permit', 'Game drives', 'Water'],
    exclusions: ['International flights', 'Insurance', 'Visas', 'Drinks', 'Border fees', 'Tips'],
  },

};

// Helper: get tours by country
function getToursByCountry(country) {
  return Object.values(TOURS).filter(t => t.country === country);
}

// Helper: get tour by id
function getTourById(id) {
  return TOURS[id] || null;
}
